import { RoleType } from '@/utils/permission'

export default [
  {
    component: 'CNavTitle',
    name: '配置',
  },
  {
    component: 'CNavItem',
    name: '全局配置',
    to: '/admin/config/global',
    icon: 'cil-settings',
    roles: [RoleType.Config],
  },
  {
    component: 'CNavItem',
    name: '登录配置',
    to: '/admin/config/login',
    icon: 'cil-lock-locked',
    roles: [RoleType.Config],
  },
  {
    component: 'CNavItem',
    name: '道具配置',
    to: '/admin/config/item',
    icon: 'cil-puzzle',
  },
  {
    component: 'CNavItem',
    name: '抽水配置',
    to: '/admin/config/water',
    icon: 'cil-dollar',
  },
  {
    component: 'CNavItem',
    name: '充值奖励配置',
    to: '/admin/config/charge-reward',
    icon: 'cil-star',
  },
  {
    component: 'CNavTitle',
    name: '管理',
  },
  {
    component: 'CNavItem',
    name: '普通用户管理',
    to: '/admin/users',
    icon: 'cil-user',
    roles: [RoleType.UserInfos],
  },
  {
    component: 'CNavItem',
    name: '代理用户管理',
    to: '/admin/proxyusers',
    icon: 'cil-user',
    roles: [RoleType.UserInfos],
  },
  {
    component: 'CNavItem',
    name: '后台用户管理',
    to: '/admin/adminusers',
    icon: 'cil-user',
    roles: [RoleType.Admin],
  },
  {
    component: 'CNavItem',
    name: '机器人用户管理',
    to: '/admin/robotusers',
    icon: 'cil-people',
    roles: [RoleType.Robot],
  },
  {
    component: 'CNavItem',
    name: '注册审核',
    to: '/admin/users/register-audit',
    icon: 'cil-check-circle',
    roles: [RoleType.RegisterAudit],
  },
  {
    component: 'CNavItem',
    name: '匹配管理',
    to: '/admin/groups',
    icon: 'cil-people',
  },
  {
    component: 'CNavItem',
    name: '房间管理',
    to: '/admin/rooms',
    icon: 'cil-layers',
  },
  {
    component: 'CNavItem',
    name: '邮件管理',
    to: '/admin/mail',
    icon: 'cil-envelope-open',
  },
  {
    component: 'CNavTitle',
    name: '比赛',
  },
  {
    component: 'CNavItem',
    name: '比赛管理',
    to: '/admin/matches',
    icon: 'cil-star',
  },
  {
    component: 'CNavTitle',
    name: '客服',
  },
  {
    component: 'CNavItem',
    name: '聊天',
    to: '/admin/chat',
    icon: 'cil-chat-bubble',
    roles: [RoleType.CustomerChatManager, RoleType.CustomerChat],
  },
  {
    component: 'CNavTitle',
    name: '新闻',
  },
  {
    component: 'CNavItem',
    name: '新闻管理',
    to: '/admin/news',
    icon: 'cil-file',
    roles: [RoleType.News],
  },
  {
    component: 'CNavItem',
    name: '横幅管理',
    to: '/admin/news/banners',
    icon: 'cil-file',
    roles: [RoleType.News],
  },
  {
    component: 'CNavTitle',
    name: '机器人',
  },
  {
    component: 'CNavItem',
    name: '机器人管理',
    to: '/admin/robot',
    icon: 'cil-people',
    roles: [RoleType.Robot],
  },
  {
    component: 'CNavTitle',
    name: '流水',
  },
  {
    component: 'CNavItem',
    name: '用户流水',
    to: '/admin/users/serial',
    icon: 'cil-list',
    roles: [RoleType.LeaderProxy],
  },
  {
    component: 'CNavTitle',
    name: '充值/提现',
  },
  {
    component: 'CNavItem',
    name: '链信息',
    to: '/admin/charge/chains',
    icon: 'cil-link',
    roles: [RoleType.Charge],
  },
  // {
  //   component: 'CNavItem',
  //   name: '银行信息',
  //   to: '/admin/charge/banks',
  //   icon: 'cil-bank',
  // },
  // {
  //   component: 'CNavItem',
  //   name: '支行信息',
  //   to: '/admin/charge/bank-branches',
  //   icon: 'cil-building',
  // },
  // {
  //   component: 'CNavItem',
  //   name: 'PayPal信息',
  //   to: '/admin/charge/paypal',
  //   icon: 'cil-credit-card',
  // },
  // {
  //   component: 'CNavItem',
  //   name: '充值配置-银行',
  //   to: '/admin/charge/config-bank',
  //   icon: 'cil-dollar',
  // },
  {
    component: 'CNavItem',
    name: '充值配置-区块链',
    to: '/admin/charge/config-blockchain',
    icon: 'cil-cloud',
    roles: [RoleType.Charge],
  },
  {
    component: 'CNavItem',
    name: '充值配置-Apple Card',
    to: '/admin/charge/config-applecard',
    icon: 'cil-credit-card',
    roles: [RoleType.Charge],
  },
  // {
  //   component: 'CNavItem',
  //   name: '充值配置-PayPal',
  //   to: '/admin/charge/config-paypal',
  //   icon: 'cil-wallet',
  // },
  // {
  //   component: 'CNavItem',
  //   name: '提现配置-银行',
  //   to: '/admin/charge/withdraw-config-bank',
  //   icon: 'cil-dollar',
  // },
  {
    component: 'CNavItem',
    name: '提现配置-区块链',
    to: '/admin/charge/withdraw-config-blockchain',
    icon: 'cil-cloud',
    roles: [RoleType.Charge],
  },
  {
    component: 'CNavItem',
    name: '提现主地址',
    to: '/admin/charge/withdraw-chain-main-address',
    icon: 'cil-home',
    roles: [RoleType.Charge],
  },
  // {
  //   component: 'CNavItem',
  //   name: '提现配置-PayPal',
  //   to: '/admin/charge/withdraw-config-paypal',
  //   icon: 'cil-wallet',
  // },
  {
    component: 'CNavItem',
    name: '充值/提现审核',
    to: '/admin/charge/orders',
    icon: 'cil-check-alt',
    roles: [RoleType.ChargeConfirm],
  },
  {
    component: 'CNavItem',
    name: '奖池管理',
    to: '/admin/charge/pot',
    icon: 'cil-puzzle',
    roles: [RoleType.Pot],
  },
]
