server:
  port: 7350
  grpc_port: 7349
  websocket_port: 7351

database:
  host: ${DB_HOST:dev_cockroach}
  port: ${DB_PORT:26257}
  user: ${DB_USER:root}
  password: ${DB_PASSWORD:}
  name: ${DB_NAME:nakama}
  sslmode: disable
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: ${REDIS_HOST:dev_redis}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  db: 2

log:
  level: debug
  format: json
