/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  admin_permission: () => import("@/views/admin/permission/index.vue"),
  admin_role: () => import("@/views/admin/role/index.vue"),
  admin_list: () => import("@/views/admin_list/index.vue"),
  content_banner: () => import("@/views/content/banner/index.vue"),
  content_category: () => import("@/views/content/category/index.vue"),
  content_list: () => import("@/views/content/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  operations_log: () => import("@/views/operations_log/index.vue"),
  settings_email: () => import("@/views/settings/email/index.vue"),
  settings_language: () => import("@/views/settings/language/index.vue"),
  settings_user: () => import("@/views/settings/user/index.vue"),
  storage_config: () => import("@/views/storage/config/index.vue"),
  storage_records: () => import("@/views/storage/records/index.vue"),
  "support_send-email": () => import("@/views/support/send-email/index.vue"),
  user_approval: () => import("@/views/user_approval/index.vue"),
  user_manage: () => import("@/views/user_manage/index.vue"),
};
