/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '无权限',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '页面不存在',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '服务器错误',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/admin',
    component: 'layout.base',
    meta: {
      title: '管理员',
      i18nKey: 'route.admin',
      icon: 'mdi:shield-account',
      order: 6
    },
    children: [
      {
        name: 'admin_list',
        path: '/admin/list',
        component: 'view.admin_list',
        meta: {
          title: '管理员列表',
          i18nKey: 'route.admin_list',
          icon: 'carbon:user'
        }
      },
      {
        name: 'admin_permission',
        path: '/admin/permission',
        component: 'view.admin_permission',
        meta: {
          title: '权限管理',
          i18nKey: 'route.admin_permission',
          icon: 'carbon:locked'
        }
      },
      {
        name: 'admin_role',
        path: '/admin/role',
        component: 'view.admin_role',
        meta: {
          title: '角色管理',
          i18nKey: 'route.admin_role',
          icon: 'carbon:user-role'
        }
      }
    ]
  },
  {
    name: 'content',
    path: '/content',
    component: 'layout.base',
    meta: {
      title: '内容管理',
      i18nKey: 'route.content',
      icon: 'mdi:file-document-outline',
      order: 3
    },
    children: [
      {
        name: 'content_banner',
        path: '/content/banner',
        component: 'view.content_banner',
        meta: {
          title: 'Banner管理',
          i18nKey: 'route.content_banner',
          icon: 'carbon:image'
        }
      },
      {
        name: 'content_category',
        path: '/content/category',
        component: 'view.content_category',
        meta: {
          title: '内容分类',
          i18nKey: 'route.content_category',
          icon: 'carbon:folder'
        }
      },
      {
        name: 'content_list',
        path: '/content/list',
        component: 'view.content_list',
        meta: {
          title: '内容列表',
          i18nKey: 'route.content_list',
          icon: 'carbon:document'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: '首页',
      i18nKey: 'route.home',
      icon: 'mdi:home',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: '内嵌页面',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login)?',
    component: 'layout.blank$view.login',
    meta: {
      title: '登录',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    },
    props: true
  },
  {
    name: 'operations',
    path: '/operations',
    component: 'layout.base',
    meta: {
      title: '其他',
      i18nKey: 'route.operations',
      icon: 'carbon:activity',
      order: 4
    },
    children: [
      {
        name: 'operations_log',
        path: '/operations/log',
        component: 'view.operations_log',
        meta: {
          title: '操作日志',
          i18nKey: 'route.operations_log',
          icon: 'carbon:document'
        }
      }
    ]
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base',
    meta: {
      title: '系统设置',
      i18nKey: 'route.settings',
      icon: 'mdi:cog',
      order: 8
    },
    children: [
      {
        name: 'settings_email',
        path: '/settings/email',
        component: 'view.settings_email',
        meta: {
          title: '邮件配置',
          i18nKey: 'route.settings_email',
          icon: 'carbon:email'
        }
      },
      {
        name: 'settings_general',
        path: '/settings/general',
        component: 'view.settings_general',
        meta: {
          title: '基础设置',
          i18nKey: 'route.settings_general',
          icon: 'carbon:settings-adjust'
        }
      },
      {
        name: 'settings_language',
        path: '/settings/language',
        component: 'view.settings_language',
        meta: {
          title: '语言设置',
          i18nKey: 'route.settings_language',
          icon: 'carbon:language'
        }
      }
    ]
  },
  {
    name: 'storage',
    path: '/storage',
    component: 'layout.base',
    meta: {
      title: '存储管理',
      i18nKey: 'route.storage',
      icon: 'mdi:cloud-upload',
      order: 7
    },
    children: [
      {
        name: 'storage_config',
        path: '/storage/config',
        component: 'view.storage_config',
        meta: {
          title: '存储配置',
          i18nKey: 'route.storage_config',
          icon: 'carbon:cloud-upload'
        }
      },
      {
        name: 'storage_records',
        path: '/storage/records',
        component: 'view.storage_records',
        meta: {
          title: '上传记录',
          i18nKey: 'route.storage_records',
          icon: 'carbon:document'
        }
      }
    ]
  },
  {
    name: 'support',
    path: '/support',
    component: 'layout.base',
    meta: {
      title: '客服管理',
      i18nKey: 'route.support',
      icon: 'mdi:headset',
      order: 5
    },
    children: [
      {
        name: 'support_send-email',
        path: '/support/send-email',
        component: 'view.support_send-email',
        meta: {
          title: '发送邮件',
          i18nKey: 'route.support_send-email',
          icon: 'carbon:email'
        }
      }
    ]
  }
];
