[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:nakama]
command=/nakama/nakama --database.address=root@dev_cockroach:26257/nakama --runtime.path=/nakama/data/modules/ --socket.server_key=dev_server_key_2026 --session.encryption_key=dev_session_key_2026 --runtime.http_key=dev_http_key_2026 --console.username=admin --console.password=admin123
autostart=true
autorestart=true
stdout_logfile=/var/log/nakama.log
stderr_logfile=/var/log/nakama.err

[program:gin]
command=/app/webadmin
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/gin.log
stderr_logfile=/var/log/gin.err
environment=TZ="Asia/Shanghai"
